// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: mirage/v1/mirage.proto

// Mirage — wire protocol for the lazy workspace filesystem.
// A full local-looking filesystem on the sandbox that is secretly remote:
// files materialize only when touched.
//
// CONNECTION MODEL (see design §3):
//   The CLIENT opens exactly one bidirectional stream by calling Connect().
//   The client is behind NAT/firewall; the server NEVER dials the client.
//   Once the stream is open it is FULL-DUPLEX: the server originates
//   requests (e.g. ChunkRequest) by sending ServerFrame down the stream the
//   client opened. This separates "who opens the socket" (client) from
//   "who originates a request" (either side).
//
// SECURITY (see design §6):
//   Reads are CHUNK-HASH based, not path based. The server can only ask for
//   chunk hashes present in the index the client published. It cannot name a
//   path like ~/.ssh/id_rsa, because secret files are excluded at index-build
//   time and their chunks are never published.

package miragev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Mirage_Connect_FullMethodName = "/mirage.v1.Mirage/Connect"
)

// MirageClient is the client API for Mirage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MirageClient interface {
	// The ONLY entry point. Client initiates; both sides then exchange frames.
	// ClientFrame flows client->server, ServerFrame flows server->client.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientFrame, ServerFrame], error)
}

type mirageClient struct {
	cc grpc.ClientConnInterface
}

func NewMirageClient(cc grpc.ClientConnInterface) MirageClient {
	return &mirageClient{cc}
}

func (c *mirageClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientFrame, ServerFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Mirage_ServiceDesc.Streams[0], Mirage_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientFrame, ServerFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Mirage_ConnectClient = grpc.BidiStreamingClient[ClientFrame, ServerFrame]

// MirageServer is the server API for Mirage service.
// All implementations must embed UnimplementedMirageServer
// for forward compatibility.
type MirageServer interface {
	// The ONLY entry point. Client initiates; both sides then exchange frames.
	// ClientFrame flows client->server, ServerFrame flows server->client.
	Connect(grpc.BidiStreamingServer[ClientFrame, ServerFrame]) error
	mustEmbedUnimplementedMirageServer()
}

// UnimplementedMirageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMirageServer struct{}

func (UnimplementedMirageServer) Connect(grpc.BidiStreamingServer[ClientFrame, ServerFrame]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedMirageServer) mustEmbedUnimplementedMirageServer() {}
func (UnimplementedMirageServer) testEmbeddedByValue()                {}

// UnsafeMirageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MirageServer will
// result in compilation errors.
type UnsafeMirageServer interface {
	mustEmbedUnimplementedMirageServer()
}

func RegisterMirageServer(s grpc.ServiceRegistrar, srv MirageServer) {
	// If the following call panics, it indicates UnimplementedMirageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Mirage_ServiceDesc, srv)
}

func _Mirage_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MirageServer).Connect(&grpc.GenericServerStream[ClientFrame, ServerFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Mirage_ConnectServer = grpc.BidiStreamingServer[ClientFrame, ServerFrame]

// Mirage_ServiceDesc is the grpc.ServiceDesc for Mirage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mirage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mirage.v1.Mirage",
	HandlerType: (*MirageServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Mirage_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "mirage/v1/mirage.proto",
}
