// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mirage/v1/mirage.proto

// Mirage — wire protocol for the lazy workspace filesystem.
// A full local-looking filesystem on the sandbox that is secretly remote:
// files materialize only when touched.
//
// CONNECTION MODEL (see design §3):
//   The CLIENT opens exactly one bidirectional stream by calling Connect().
//   The client is behind NAT/firewall; the server NEVER dials the client.
//   Once the stream is open it is FULL-DUPLEX: the server originates
//   requests (e.g. ChunkRequest) by sending ServerFrame down the stream the
//   client opened. This separates "who opens the socket" (client) from
//   "who originates a request" (either side).
//
// SECURITY (see design §6):
//   Reads are CHUNK-HASH based, not path based. The server can only ask for
//   chunk hashes present in the index the client published. It cannot name a
//   path like ~/.ssh/id_rsa, because secret files are excluded at index-build
//   time and their chunks are never published.

package miragev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileChange_Kind int32

const (
	FileChange_MODIFY FileChange_Kind = 0
	FileChange_CREATE FileChange_Kind = 1
	FileChange_DELETE FileChange_Kind = 2
)

// Enum value maps for FileChange_Kind.
var (
	FileChange_Kind_name = map[int32]string{
		0: "MODIFY",
		1: "CREATE",
		2: "DELETE",
	}
	FileChange_Kind_value = map[string]int32{
		"MODIFY": 0,
		"CREATE": 1,
		"DELETE": 2,
	}
)

func (x FileChange_Kind) Enum() *FileChange_Kind {
	p := new(FileChange_Kind)
	*p = x
	return p
}

func (x FileChange_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileChange_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_mirage_v1_mirage_proto_enumTypes[0].Descriptor()
}

func (FileChange_Kind) Type() protoreflect.EnumType {
	return &file_mirage_v1_mirage_proto_enumTypes[0]
}

func (x FileChange_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileChange_Kind.Descriptor instead.
func (FileChange_Kind) EnumDescriptor() ([]byte, []int) {
	return file_mirage_v1_mirage_proto_rawDescGZIP(), []int{10, 0}
}

type FileApply_Status int32

const (
	FileApply_APPLIED  FileApply_Status = 0
	FileApply_CONFLICT FileApply_Status = 1
	FileApply_REJECTED FileApply_Status = 2
)

// Enum value maps for FileApply_Status.
var (
	FileApply_Status_name = map[int32]string{
		0: "APPLIED",
		1: "CONFLICT",
		2: "REJECTED",
	}
	FileApply_Status_value = map[string]int32{
		"APPLIED":  0,
		"CONFLICT": 1,
		"REJECTED": 2,
	}
)

func (x FileApply_Status) Enum() *FileApply_Status {
	p := new(FileApply_Status)
	*p = x
	return p
}

func (x FileApply_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileApply_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_mirage_v1_mirage_proto_enumTypes[1].Descriptor()
}

func (FileApply_Status) Type() protoreflect.EnumType {
	return &file_mirage_v1_mirage_proto_enumTypes[1]
}

func (x FileApply_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileApply_Status.Descriptor instead.
func (FileApply_Status) EnumDescriptor() ([]byte, []int) {
	return file_mirage_v1_mirage_proto_rawDescGZIP(), []int{12, 0}
}

type AgentEvent_Kind int32

const (
	AgentEvent_ASSISTANT_TEXT AgentEvent_Kind = 0
	AgentEvent_TOOL_BEGIN     AgentEvent_Kind = 1
	AgentEvent_TOOL_END       AgentEvent_Kind = 2
	AgentEvent_STATUS         AgentEvent_Kind = 3
)

// Enum value maps for AgentEvent_Kind.
var (
	AgentEvent_Kind_name = map[int32]string{
		0: "ASSISTANT_TEXT",
		1: "TOOL_BEGIN",
		2: "TOOL_END",
		3: "STATUS",
	}
	AgentEvent_Kind_value = map[string]int32{
		"ASSISTANT_TEXT": 0,
		"TOOL_BEGIN":     1,
		"TOOL_END":       2,
		"STATUS":         3,
	}
)

func (x AgentEvent_Kind) Enum() *AgentEvent_Kind {
	p := new(AgentEvent_Kind)
	*p = x
	return p
}

func (x AgentEvent_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentEvent_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_mirage_v1_mirage_proto_enumTypes[2].Descriptor()
}

func (AgentEvent_Kind) Type() protoreflect.EnumType {
	return &file_mirage_v1_mirage_proto_enumTypes[2]
}

func (x AgentEvent_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentEvent_Kind.Descriptor instead.
func (AgentEvent_Kind) EnumDescriptor() ([]byte, []int) {
	return file_mirage_v1_mirage_proto_rawDescGZIP(), []int{15, 0}
}

// Sent by the client (the side that opened the connection).
type ClientFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientFrame_Hello
	//	*ClientFrame_IndexPublish
	//	*ClientFrame_ChunkResponse
	//	*ClientFrame_WriteBackResult
	//	*ClientFrame_PermissionResult
	//	*ClientFrame_UserInput
	//	*ClientFrame_Heartbeat
	Payload       isClientFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientFrame) Reset() {
	*x = ClientFrame{}
	mi := &file_mirage_v1_mirage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFrame) ProtoMessage() {}

func (x *ClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_mirage_v1_mirage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFrame.ProtoReflect.Descriptor instead.
func (*ClientFrame) Descriptor() ([]byte, []int) {
	return file_mirage_v1_mirage_proto_rawDescGZIP(), []int{0}
}

func (x *ClientFrame) GetPayload() isClientFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientFrame) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*ClientFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ClientFrame) GetIndexPublish() *IndexPublish {
	if x != nil {
		if x, ok := x.Payload.(*ClientFrame_IndexPublish); ok {
			return x.IndexPublish
		}
	}
	return nil
}

func (x *ClientFrame) GetChunkResponse() *ChunkResponse {
	if x != nil {
		if x, ok := x.Payload.(*ClientFrame_ChunkResponse); ok {
			return x.ChunkResponse
		}
	}
	return nil
}

func (x *ClientFrame) GetWriteBackResult() *WriteBackResult {
	if x != nil {
		if x, ok := x.Payload.(*ClientFrame_WriteBackResult); ok {
			return x.WriteBackResult
		}
	}
	return nil
}

func (x *ClientFrame) GetPermissionResult() *PermissionResult {
	if x != nil {
		if x, ok := x.Payload.(*ClientFrame_PermissionResult); ok {
			return x.PermissionResult
		}
	}
	return nil
}

func (x *ClientFrame) GetUserInput() *UserInput {
	if x != nil {
		if x, ok := x.Payload.(*ClientFrame_UserInput); ok {
			return x.UserInput
		}
	}
	return nil
}

func (x *ClientFrame) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*ClientFrame_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isClientFrame_Payload interface {
	isClientFrame_Payload()
}

type ClientFrame_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"` // first frame: auth + workspace handshake
}

type ClientFrame_IndexPublish struct {
	IndexPublish *IndexPublish `protobuf:"bytes,2,opt,name=index_publish,json=indexPublish,proto3,oneof"` // the desync index (manifest of chunk hashes)
}

type ClientFrame_ChunkResponse struct {
	ChunkResponse *ChunkResponse `protobuf:"bytes,3,opt,name=chunk_response,json=chunkResponse,proto3,oneof"` // answer to a server ChunkRequest
}

type ClientFrame_WriteBackResult struct {
	WriteBackResult *WriteBackResult `protobuf:"bytes,4,opt,name=write_back_result,json=writeBackResult,proto3,oneof"` // result of applying a write-back batch
}

type ClientFrame_PermissionResult struct {
	PermissionResult *PermissionResult `protobuf:"bytes,5,opt,name=permission_result,json=permissionResult,proto3,oneof"` // user's answer to a prompt
}

type ClientFrame_UserInput struct {
	UserInput *UserInput `protobuf:"bytes,6,opt,name=user_input,json=userInput,proto3,oneof"` // user typed something in the TUI
}

type ClientFrame_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,7,opt,name=heartbeat,proto3,oneof"`
}

func (*ClientFrame_Hello) isClientFrame_Payload() {}

func (*ClientFrame_IndexPublish) isClientFrame_Payload() {}

func (*ClientFrame_ChunkResponse) isClientFrame_Payload() {}

func (*ClientFrame_WriteBackResult) isClientFrame_Payload() {}

func (*ClientFrame_PermissionResult) isClientFrame_Payload() {}

func (*ClientFrame_UserInput) isClientFrame_Payload() {}

func (*ClientFrame_Heartbeat) isClientFrame_Payload() {}

// Sent by the server (the sandbox) — over the stream the client opened.
type ServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerFrame_HelloAck
	//	*ServerFrame_ChunkRequest
	//	*ServerFrame_WriteBackBatch
	//	*ServerFrame_PermissionRequest
	//	*ServerFrame_AgentEvent
	//	*ServerFrame_Heartbeat
	Payload       isServerFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_mirage_v1_mirage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_mirage_v1_mirage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_mirage_v1_mirage_proto_rawDescGZIP(), []int{1}
}

func (x *ServerFrame) GetPayload() isServerFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerFrame) GetHelloAck() *HelloAck {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_HelloAck); ok {
			return x.HelloAck
		}
	}
	return nil
}

func (x *ServerFrame) GetChunkRequest() *ChunkRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_ChunkRequest); ok {
			return x.ChunkRequest
		}
	}
	return nil
}

func (x *ServerFrame) GetWriteBackBatch() *WriteBackBatch {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_WriteBackBatch); ok {
			return x.WriteBackBatch
		}
	}
	return nil
}

func (x *ServerFrame) GetPermissionRequest() *PermissionRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_PermissionRequest); ok {
			return x.PermissionRequest
		}
	}
	return nil
}

func (x *ServerFrame) GetAgentEvent() *AgentEvent {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_AgentEvent); ok {
			return x.AgentEvent
		}
	}
	return nil
}

func (x *ServerFrame) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isServerFrame_Payload interface {
	isServerFrame_Payload()
}

type ServerFrame_HelloAck struct {
	HelloAck *HelloAck `protobuf:"bytes,1,opt,name=hello_ack,json=helloAck,proto3,oneof"`
}

type ServerFrame_ChunkRequest struct {
	ChunkRequest *ChunkRequest `protobuf:"bytes,2,opt,name=chunk_request,json=chunkRequest,proto3,oneof"` // server needs a chunk to satisfy a read
}

type ServerFrame_WriteBackBatch struct {
	WriteBackBatch *WriteBackBatch `protobuf:"bytes,3,opt,name=write_back_batch,json=writeBackBatch,proto3,oneof"` // sandbox edited files; apply to client workspace
}

type ServerFrame_PermissionRequest struct {
	PermissionRequest *PermissionRequest `protobuf:"bytes,4,opt,name=permission_request,json=permissionRequest,proto3,oneof"` // gate a risky action on the client
}

type ServerFrame_AgentEvent struct {
	AgentEvent *AgentEvent `protobuf:"bytes,5,opt,name=agent_event,json=agentEvent,proto3,oneof"` // stream agent output to the TUI
}

type ServerFrame_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,6,opt,name=heartbeat,proto3,oneof"`
}

func (*ServerFrame_HelloAck) isServerFrame_Payload() {}

func (*ServerFrame_ChunkRequest) isServerFrame_Payload() {}

func (*ServerFrame_WriteBackBatch) isServerFrame_Payload() {}

func (*ServerFrame_PermissionRequest) isServerFrame_Payload() {}

func (*ServerFrame_AgentEvent) isServerFrame_Payload() {}

func (*ServerFrame_Heartbeat) isServerFrame_Payload() {}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"` // short-lived, connection-bound
	ClientVersion string                 `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"` // "windows" | "darwin"
	Workspace     *WorkspaceMeta         `protobuf:"bytes,4,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_mirage_v1_mirage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_mirage_v1_mirage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_mirage_v1_mirage_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *Hello) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *Hello) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Hello) GetWorkspace() *WorkspaceMeta {
	if x != nil {
		return x.Workspace
	}
	return nil
}

type WorkspaceMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootName      string                 `protobuf:"bytes,1,opt,name=root_name,json=rootName,proto3" json:"root_name,omitempty"` // display name only; never an absolute host path
	IsGit         bool                   `protobuf:"varint,2,opt,name=is_git,json=isGit,proto3" json:"is_git,omitempty"`
	GitRemoteUrl  string                 `protobuf:"bytes,3,opt,name=git_remote_url,json=gitRemoteUrl,proto3" json:"git_remote_url,omitempty"`    // empty if none reachable
	GitHeadCommit string                 `protobuf:"bytes,4,opt,name=git_head_commit,json=gitHeadCommit,proto3" json:"git_head_commit,omitempty"` // commit the working-tree delta is relative to
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceMeta) Reset() {
	*x = WorkspaceMeta{}
	mi := &file_mirage_v1_mirage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceMeta) ProtoMessage() {}

func (x *WorkspaceMeta) ProtoReflect() protoreflect.Message {
	mi := &file_mirage_v1_mirage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceMeta.ProtoReflect.Descriptor instead.
func (*WorkspaceMeta) Descriptor() ([]byte, []int) {
	return file_mirage_v1_mirage_proto_rawDescGZIP(), []int{3}
}

func (x *WorkspaceMeta) GetRootName() string {
	if x != nil {
		return x.RootName
	}
	return ""
}

func (x *WorkspaceMeta) GetIsGit() bool {
	if x != nil {
		return x.IsGit
	}
	return false
}

func (x *WorkspaceMeta) GetGitRemoteUrl() string {
	if x != nil {
		return x.GitRemoteUrl
	}
	return ""
}

func (x *WorkspaceMeta) GetGitHeadCommit() string {
	if x != nil {
		return x.GitHeadCommit
	}
	return ""
}

type HelloAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Resume        bool                   `protobuf:"varint,2,opt,name=resume,proto3" json:"resume,omitempty"` // true if a warm snapshot was reused
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_mirage_v1_mirage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_mirage_v1_mirage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_mirage_v1_mirage_proto_rawDescGZIP(), []int{4}
}

func (x *HelloAck) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *HelloAck) GetResume() bool {
	if x != nil {
		return x.Resume
	}
	return false
}

// The desync index: the ordered list of chunk hashes that make up the tree
// (or, in the git fast-path, just the working-tree delta). Small relative to
// the tree. Sent up front; chunk *contents* are faulted lazily afterward.
type IndexPublish struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Caidx         []byte                 `protobuf:"bytes,1,opt,name=caidx,proto3" json:"caidx,omitempty"` // serialized desync index (or a chunked stream of it)
	TotalChunks   uint32                 `protobuf:"varint,2,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	TotalBytes    uint64                 `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"` // logical size of the materialized tree
	IsDelta       bool                   `protobuf:"varint,4,opt,name=is_delta,json=isDelta,proto3" json:"is_delta,omitempty"`          // true => overlay on top of a git clone
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexPublish) Reset() {
	*x = IndexPublish{}
	mi := &file_mirage_v1_mirage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexPublish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexPublish) ProtoMessage() {}

func (x *IndexPublish) ProtoReflect() protoreflect.Message {
	mi := &file_mirage_v1_mirage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexPublish.ProtoReflect.Descriptor instead.
func (*IndexPublish) Descriptor() ([]byte, []int) {
	return file_mirage_v1_mirage_proto_rawDescGZIP(), []int{5}
}

func (x *IndexPublish) GetCaidx() []byte {
	if x != nil {
		return x.Caidx
	}
	return nil
}

func (x *IndexPublish) GetTotalChunks() uint32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *IndexPublish) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *IndexPublish) GetIsDelta() bool {
	if x != nil {
		return x.IsDelta
	}
	return false
}

type ChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ChunkHashes   [][]byte               `protobuf:"bytes,2,rep,name=chunk_hashes,json=chunkHashes,proto3" json:"chunk_hashes,omitempty"` // batch of content hashes the FUSE layer faulted on
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkRequest) Reset() {
	*x = ChunkRequest{}
	mi := &file_mirage_v1_mirage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkRequest) ProtoMessage() {}

func (x *ChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mirage_v1_mirage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkRequest.ProtoReflect.Descriptor instead.
func (*ChunkRequest) Descriptor() ([]byte, []int) {
	return file_mirage_v1_mirage_proto_rawDescGZIP(), []int{6}
}

func (x *ChunkRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ChunkRequest) GetChunkHashes() [][]byte {
	if x != nil {
		return x.ChunkHashes
	}
	return nil
}

type ChunkResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Chunks    []*Chunk               `protobuf:"bytes,2,rep,name=chunks,proto3" json:"chunks,omitempty"`
	// Client MUST only serve hashes present in the published index. Unknown or
	// excluded hashes => error, not data.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkResponse) Reset() {
	*x = ChunkResponse{}
	mi := &file_mirage_v1_mirage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkResponse) ProtoMessage() {}

func (x *ChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mirage_v1_mirage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkResponse.ProtoReflect.Descriptor instead.
func (*ChunkResponse) Descriptor() ([]byte, []int) {
	return file_mirage_v1_mirage_proto_rawDescGZIP(), []int{7}
}

func (x *ChunkResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ChunkResponse) GetChunks() []*Chunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *ChunkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"` // content hash (id)
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // raw chunk bytes (may be desync-compressed)
	Compressed    bool                   `protobuf:"varint,3,opt,name=compressed,proto3" json:"compressed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_mirage_v1_mirage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_mirage_v1_mirage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_mirage_v1_mirage_proto_rawDescGZIP(), []int{8}
}

func (x *Chunk) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Chunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Chunk) GetCompressed() bool {
	if x != nil {
		return x.Compressed
	}
	return false
}

type WriteBackBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       uint64                 `protobuf:"varint,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Changes       []*FileChange          `protobuf:"bytes,2,rep,name=changes,proto3" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteBackBatch) Reset() {
	*x = WriteBackBatch{}
	mi := &file_mirage_v1_mirage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteBackBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBackBatch) ProtoMessage() {}

func (x *WriteBackBatch) ProtoReflect() protoreflect.Message {
	mi := &file_mirage_v1_mirage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBackBatch.ProtoReflect.Descriptor instead.
func (*WriteBackBatch) Descriptor() ([]byte, []int) {
	return file_mirage_v1_mirage_proto_rawDescGZIP(), []int{9}
}

func (x *WriteBackBatch) GetBatchId() uint64 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

func (x *WriteBackBatch) GetChanges() []*FileChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

type FileChange struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           FileChange_Kind        `protobuf:"varint,1,opt,name=kind,proto3,enum=mirage.v1.FileChange_Kind" json:"kind,omitempty"`
	RelPath        string                 `protobuf:"bytes,2,opt,name=rel_path,json=relPath,proto3" json:"rel_path,omitempty"`                        // relative to workspace root; traversal outside rejected
	BaseHash       []byte                 `protobuf:"bytes,3,opt,name=base_hash,json=baseHash,proto3" json:"base_hash,omitempty"`                     // content hash at publish time, for conflict detection
	NewChunkHashes [][]byte               `protobuf:"bytes,4,rep,name=new_chunk_hashes,json=newChunkHashes,proto3" json:"new_chunk_hashes,omitempty"` // new content as chunks (data via ChunkRequest reverse, or inline)
	InlineChunks   []*Chunk               `protobuf:"bytes,5,rep,name=inline_chunks,json=inlineChunks,proto3" json:"inline_chunks,omitempty"`         // small files may inline their chunks
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileChange) Reset() {
	*x = FileChange{}
	mi := &file_mirage_v1_mirage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChange) ProtoMessage() {}

func (x *FileChange) ProtoReflect() protoreflect.Message {
	mi := &file_mirage_v1_mirage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChange.ProtoReflect.Descriptor instead.
func (*FileChange) Descriptor() ([]byte, []int) {
	return file_mirage_v1_mirage_proto_rawDescGZIP(), []int{10}
}

func (x *FileChange) GetKind() FileChange_Kind {
	if x != nil {
		return x.Kind
	}
	return FileChange_MODIFY
}

func (x *FileChange) GetRelPath() string {
	if x != nil {
		return x.RelPath
	}
	return ""
}

func (x *FileChange) GetBaseHash() []byte {
	if x != nil {
		return x.BaseHash
	}
	return nil
}

func (x *FileChange) GetNewChunkHashes() [][]byte {
	if x != nil {
		return x.NewChunkHashes
	}
	return nil
}

func (x *FileChange) GetInlineChunks() []*Chunk {
	if x != nil {
		return x.InlineChunks
	}
	return nil
}

type WriteBackResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       uint64                 `protobuf:"varint,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Applied       []*FileApply           `protobuf:"bytes,2,rep,name=applied,proto3" json:"applied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteBackResult) Reset() {
	*x = WriteBackResult{}
	mi := &file_mirage_v1_mirage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteBackResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBackResult) ProtoMessage() {}

func (x *WriteBackResult) ProtoReflect() protoreflect.Message {
	mi := &file_mirage_v1_mirage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBackResult.ProtoReflect.Descriptor instead.
func (*WriteBackResult) Descriptor() ([]byte, []int) {
	return file_mirage_v1_mirage_proto_rawDescGZIP(), []int{11}
}

func (x *WriteBackResult) GetBatchId() uint64 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

func (x *WriteBackResult) GetApplied() []*FileApply {
	if x != nil {
		return x.Applied
	}
	return nil
}

type FileApply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RelPath       string                 `protobuf:"bytes,1,opt,name=rel_path,json=relPath,proto3" json:"rel_path,omitempty"`
	Status        FileApply_Status       `protobuf:"varint,2,opt,name=status,proto3,enum=mirage.v1.FileApply_Status" json:"status,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileApply) Reset() {
	*x = FileApply{}
	mi := &file_mirage_v1_mirage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileApply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileApply) ProtoMessage() {}

func (x *FileApply) ProtoReflect() protoreflect.Message {
	mi := &file_mirage_v1_mirage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileApply.ProtoReflect.Descriptor instead.
func (*FileApply) Descriptor() ([]byte, []int) {
	return file_mirage_v1_mirage_proto_rawDescGZIP(), []int{12}
}

func (x *FileApply) GetRelPath() string {
	if x != nil {
		return x.RelPath
	}
	return ""
}

func (x *FileApply) GetStatus() FileApply_Status {
	if x != nil {
		return x.Status
	}
	return FileApply_APPLIED
}

func (x *FileApply) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type PermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"` // e.g. "run: rm -rf build/" or "apply 3 file changes"
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Options       []string               `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"` // e.g. ["Allow", "Allow once", "Deny"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionRequest) Reset() {
	*x = PermissionRequest{}
	mi := &file_mirage_v1_mirage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionRequest) ProtoMessage() {}

func (x *PermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mirage_v1_mirage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionRequest.ProtoReflect.Descriptor instead.
func (*PermissionRequest) Descriptor() ([]byte, []int) {
	return file_mirage_v1_mirage_proto_rawDescGZIP(), []int{13}
}

func (x *PermissionRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *PermissionRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *PermissionRequest) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *PermissionRequest) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

type PermissionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Chosen        string                 `protobuf:"bytes,2,opt,name=chosen,proto3" json:"chosen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionResult) Reset() {
	*x = PermissionResult{}
	mi := &file_mirage_v1_mirage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionResult) ProtoMessage() {}

func (x *PermissionResult) ProtoReflect() protoreflect.Message {
	mi := &file_mirage_v1_mirage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionResult.ProtoReflect.Descriptor instead.
func (*PermissionResult) Descriptor() ([]byte, []int) {
	return file_mirage_v1_mirage_proto_rawDescGZIP(), []int{14}
}

func (x *PermissionResult) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *PermissionResult) GetChosen() string {
	if x != nil {
		return x.Chosen
	}
	return ""
}

type AgentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          AgentEvent_Kind        `protobuf:"varint,1,opt,name=kind,proto3,enum=mirage.v1.AgentEvent_Kind" json:"kind,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_mirage_v1_mirage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_mirage_v1_mirage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_mirage_v1_mirage_proto_rawDescGZIP(), []int{15}
}

func (x *AgentEvent) GetKind() AgentEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return AgentEvent_ASSISTANT_TEXT
}

func (x *AgentEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type UserInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInput) Reset() {
	*x = UserInput{}
	mi := &file_mirage_v1_mirage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInput) ProtoMessage() {}

func (x *UserInput) ProtoReflect() protoreflect.Message {
	mi := &file_mirage_v1_mirage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInput.ProtoReflect.Descriptor instead.
func (*UserInput) Descriptor() ([]byte, []int) {
	return file_mirage_v1_mirage_proto_rawDescGZIP(), []int{16}
}

func (x *UserInput) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_mirage_v1_mirage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_mirage_v1_mirage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_mirage_v1_mirage_proto_rawDescGZIP(), []int{17}
}

func (x *Heartbeat) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

var File_mirage_v1_mirage_proto protoreflect.FileDescriptor

const file_mirage_v1_mirage_proto_rawDesc = "" +
	"\n" +
	"\x16mirage/v1/mirage.proto\x12\tmirage.v1\"\xc8\x03\n" +
	"\vClientFrame\x12(\n" +
	"\x05hello\x18\x01 \x01(\v2\x10.mirage.v1.HelloH\x00R\x05hello\x12>\n" +
	"\rindex_publish\x18\x02 \x01(\v2\x17.mirage.v1.IndexPublishH\x00R\findexPublish\x12A\n" +
	"\x0echunk_response\x18\x03 \x01(\v2\x18.mirage.v1.ChunkResponseH\x00R\rchunkResponse\x12H\n" +
	"\x11write_back_result\x18\x04 \x01(\v2\x1a.mirage.v1.WriteBackResultH\x00R\x0fwriteBackResult\x12J\n" +
	"\x11permission_result\x18\x05 \x01(\v2\x1b.mirage.v1.PermissionResultH\x00R\x10permissionResult\x125\n" +
	"\n" +
	"user_input\x18\x06 \x01(\v2\x14.mirage.v1.UserInputH\x00R\tuserInput\x124\n" +
	"\theartbeat\x18\a \x01(\v2\x14.mirage.v1.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"\x92\x03\n" +
	"\vServerFrame\x122\n" +
	"\thello_ack\x18\x01 \x01(\v2\x13.mirage.v1.HelloAckH\x00R\bhelloAck\x12>\n" +
	"\rchunk_request\x18\x02 \x01(\v2\x17.mirage.v1.ChunkRequestH\x00R\fchunkRequest\x12E\n" +
	"\x10write_back_batch\x18\x03 \x01(\v2\x19.mirage.v1.WriteBackBatchH\x00R\x0ewriteBackBatch\x12M\n" +
	"\x12permission_request\x18\x04 \x01(\v2\x1c.mirage.v1.PermissionRequestH\x00R\x11permissionRequest\x128\n" +
	"\vagent_event\x18\x05 \x01(\v2\x15.mirage.v1.AgentEventH\x00R\n" +
	"agentEvent\x124\n" +
	"\theartbeat\x18\x06 \x01(\v2\x14.mirage.v1.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"\x9b\x01\n" +
	"\x05Hello\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\x12%\n" +
	"\x0eclient_version\x18\x02 \x01(\tR\rclientVersion\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x126\n" +
	"\tworkspace\x18\x04 \x01(\v2\x18.mirage.v1.WorkspaceMetaR\tworkspace\"\x91\x01\n" +
	"\rWorkspaceMeta\x12\x1b\n" +
	"\troot_name\x18\x01 \x01(\tR\brootName\x12\x15\n" +
	"\x06is_git\x18\x02 \x01(\bR\x05isGit\x12$\n" +
	"\x0egit_remote_url\x18\x03 \x01(\tR\fgitRemoteUrl\x12&\n" +
	"\x0fgit_head_commit\x18\x04 \x01(\tR\rgitHeadCommit\"A\n" +
	"\bHelloAck\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x16\n" +
	"\x06resume\x18\x02 \x01(\bR\x06resume\"\x83\x01\n" +
	"\fIndexPublish\x12\x14\n" +
	"\x05caidx\x18\x01 \x01(\fR\x05caidx\x12!\n" +
	"\ftotal_chunks\x18\x02 \x01(\rR\vtotalChunks\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x04R\n" +
	"totalBytes\x12\x19\n" +
	"\bis_delta\x18\x04 \x01(\bR\aisDelta\"P\n" +
	"\fChunkRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12!\n" +
	"\fchunk_hashes\x18\x02 \x03(\fR\vchunkHashes\"n\n" +
	"\rChunkResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12(\n" +
	"\x06chunks\x18\x02 \x03(\v2\x10.mirage.v1.ChunkR\x06chunks\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"O\n" +
	"\x05Chunk\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1e\n" +
	"\n" +
	"compressed\x18\x03 \x01(\bR\n" +
	"compressed\"\\\n" +
	"\x0eWriteBackBatch\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\x04R\abatchId\x12/\n" +
	"\achanges\x18\x02 \x03(\v2\x15.mirage.v1.FileChangeR\achanges\"\x81\x02\n" +
	"\n" +
	"FileChange\x12.\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1a.mirage.v1.FileChange.KindR\x04kind\x12\x19\n" +
	"\brel_path\x18\x02 \x01(\tR\arelPath\x12\x1b\n" +
	"\tbase_hash\x18\x03 \x01(\fR\bbaseHash\x12(\n" +
	"\x10new_chunk_hashes\x18\x04 \x03(\fR\x0enewChunkHashes\x125\n" +
	"\rinline_chunks\x18\x05 \x03(\v2\x10.mirage.v1.ChunkR\finlineChunks\"*\n" +
	"\x04Kind\x12\n" +
	"\n" +
	"\x06MODIFY\x10\x00\x12\n" +
	"\n" +
	"\x06CREATE\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x02\"\\\n" +
	"\x0fWriteBackResult\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\x04R\abatchId\x12.\n" +
	"\aapplied\x18\x02 \x03(\v2\x14.mirage.v1.FileApplyR\aapplied\"\xa6\x01\n" +
	"\tFileApply\x12\x19\n" +
	"\brel_path\x18\x01 \x01(\tR\arelPath\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.mirage.v1.FileApply.StatusR\x06status\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"1\n" +
	"\x06Status\x12\v\n" +
	"\aAPPLIED\x10\x00\x12\f\n" +
	"\bCONFLICT\x10\x01\x12\f\n" +
	"\bREJECTED\x10\x02\"~\n" +
	"\x11PermissionRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12\x18\n" +
	"\aoptions\x18\x04 \x03(\tR\aoptions\"I\n" +
	"\x10PermissionResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x16\n" +
	"\x06chosen\x18\x02 \x01(\tR\x06chosen\"\x96\x01\n" +
	"\n" +
	"AgentEvent\x12.\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1a.mirage.v1.AgentEvent.KindR\x04kind\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"D\n" +
	"\x04Kind\x12\x12\n" +
	"\x0eASSISTANT_TEXT\x10\x00\x12\x0e\n" +
	"\n" +
	"TOOL_BEGIN\x10\x01\x12\f\n" +
	"\bTOOL_END\x10\x02\x12\n" +
	"\n" +
	"\x06STATUS\x10\x03\"\x1f\n" +
	"\tUserInput\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"!\n" +
	"\tHeartbeat\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce2G\n" +
	"\x06Mirage\x12=\n" +
	"\aConnect\x12\x16.mirage.v1.ClientFrame\x1a\x16.mirage.v1.ServerFrame(\x010\x01B5Z3github.com/suman724/mirage/proto/mirage/v1;miragev1b\x06proto3"

var (
	file_mirage_v1_mirage_proto_rawDescOnce sync.Once
	file_mirage_v1_mirage_proto_rawDescData []byte
)

func file_mirage_v1_mirage_proto_rawDescGZIP() []byte {
	file_mirage_v1_mirage_proto_rawDescOnce.Do(func() {
		file_mirage_v1_mirage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mirage_v1_mirage_proto_rawDesc), len(file_mirage_v1_mirage_proto_rawDesc)))
	})
	return file_mirage_v1_mirage_proto_rawDescData
}

var file_mirage_v1_mirage_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_mirage_v1_mirage_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_mirage_v1_mirage_proto_goTypes = []any{
	(FileChange_Kind)(0),      // 0: mirage.v1.FileChange.Kind
	(FileApply_Status)(0),     // 1: mirage.v1.FileApply.Status
	(AgentEvent_Kind)(0),      // 2: mirage.v1.AgentEvent.Kind
	(*ClientFrame)(nil),       // 3: mirage.v1.ClientFrame
	(*ServerFrame)(nil),       // 4: mirage.v1.ServerFrame
	(*Hello)(nil),             // 5: mirage.v1.Hello
	(*WorkspaceMeta)(nil),     // 6: mirage.v1.WorkspaceMeta
	(*HelloAck)(nil),          // 7: mirage.v1.HelloAck
	(*IndexPublish)(nil),      // 8: mirage.v1.IndexPublish
	(*ChunkRequest)(nil),      // 9: mirage.v1.ChunkRequest
	(*ChunkResponse)(nil),     // 10: mirage.v1.ChunkResponse
	(*Chunk)(nil),             // 11: mirage.v1.Chunk
	(*WriteBackBatch)(nil),    // 12: mirage.v1.WriteBackBatch
	(*FileChange)(nil),        // 13: mirage.v1.FileChange
	(*WriteBackResult)(nil),   // 14: mirage.v1.WriteBackResult
	(*FileApply)(nil),         // 15: mirage.v1.FileApply
	(*PermissionRequest)(nil), // 16: mirage.v1.PermissionRequest
	(*PermissionResult)(nil),  // 17: mirage.v1.PermissionResult
	(*AgentEvent)(nil),        // 18: mirage.v1.AgentEvent
	(*UserInput)(nil),         // 19: mirage.v1.UserInput
	(*Heartbeat)(nil),         // 20: mirage.v1.Heartbeat
}
var file_mirage_v1_mirage_proto_depIdxs = []int32{
	5,  // 0: mirage.v1.ClientFrame.hello:type_name -> mirage.v1.Hello
	8,  // 1: mirage.v1.ClientFrame.index_publish:type_name -> mirage.v1.IndexPublish
	10, // 2: mirage.v1.ClientFrame.chunk_response:type_name -> mirage.v1.ChunkResponse
	14, // 3: mirage.v1.ClientFrame.write_back_result:type_name -> mirage.v1.WriteBackResult
	17, // 4: mirage.v1.ClientFrame.permission_result:type_name -> mirage.v1.PermissionResult
	19, // 5: mirage.v1.ClientFrame.user_input:type_name -> mirage.v1.UserInput
	20, // 6: mirage.v1.ClientFrame.heartbeat:type_name -> mirage.v1.Heartbeat
	7,  // 7: mirage.v1.ServerFrame.hello_ack:type_name -> mirage.v1.HelloAck
	9,  // 8: mirage.v1.ServerFrame.chunk_request:type_name -> mirage.v1.ChunkRequest
	12, // 9: mirage.v1.ServerFrame.write_back_batch:type_name -> mirage.v1.WriteBackBatch
	16, // 10: mirage.v1.ServerFrame.permission_request:type_name -> mirage.v1.PermissionRequest
	18, // 11: mirage.v1.ServerFrame.agent_event:type_name -> mirage.v1.AgentEvent
	20, // 12: mirage.v1.ServerFrame.heartbeat:type_name -> mirage.v1.Heartbeat
	6,  // 13: mirage.v1.Hello.workspace:type_name -> mirage.v1.WorkspaceMeta
	11, // 14: mirage.v1.ChunkResponse.chunks:type_name -> mirage.v1.Chunk
	13, // 15: mirage.v1.WriteBackBatch.changes:type_name -> mirage.v1.FileChange
	0,  // 16: mirage.v1.FileChange.kind:type_name -> mirage.v1.FileChange.Kind
	11, // 17: mirage.v1.FileChange.inline_chunks:type_name -> mirage.v1.Chunk
	15, // 18: mirage.v1.WriteBackResult.applied:type_name -> mirage.v1.FileApply
	1,  // 19: mirage.v1.FileApply.status:type_name -> mirage.v1.FileApply.Status
	2,  // 20: mirage.v1.AgentEvent.kind:type_name -> mirage.v1.AgentEvent.Kind
	3,  // 21: mirage.v1.Mirage.Connect:input_type -> mirage.v1.ClientFrame
	4,  // 22: mirage.v1.Mirage.Connect:output_type -> mirage.v1.ServerFrame
	22, // [22:23] is the sub-list for method output_type
	21, // [21:22] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_mirage_v1_mirage_proto_init() }
func file_mirage_v1_mirage_proto_init() {
	if File_mirage_v1_mirage_proto != nil {
		return
	}
	file_mirage_v1_mirage_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientFrame_Hello)(nil),
		(*ClientFrame_IndexPublish)(nil),
		(*ClientFrame_ChunkResponse)(nil),
		(*ClientFrame_WriteBackResult)(nil),
		(*ClientFrame_PermissionResult)(nil),
		(*ClientFrame_UserInput)(nil),
		(*ClientFrame_Heartbeat)(nil),
	}
	file_mirage_v1_mirage_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerFrame_HelloAck)(nil),
		(*ServerFrame_ChunkRequest)(nil),
		(*ServerFrame_WriteBackBatch)(nil),
		(*ServerFrame_PermissionRequest)(nil),
		(*ServerFrame_AgentEvent)(nil),
		(*ServerFrame_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mirage_v1_mirage_proto_rawDesc), len(file_mirage_v1_mirage_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mirage_v1_mirage_proto_goTypes,
		DependencyIndexes: file_mirage_v1_mirage_proto_depIdxs,
		EnumInfos:         file_mirage_v1_mirage_proto_enumTypes,
		MessageInfos:      file_mirage_v1_mirage_proto_msgTypes,
	}.Build()
	File_mirage_v1_mirage_proto = out.File
	file_mirage_v1_mirage_proto_goTypes = nil
	file_mirage_v1_mirage_proto_depIdxs = nil
}
